defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: darth
  password:

development:
  database: reviyou_development
  <<: *defaults

test: &test
  database: reviyou_test
  <<: *defaults

production:
  database: reviyou_development
  <<: *defaults
